spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:4399/pasteme
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: username
    password: password
    hikari:
      driver-class-name: org.sqlite.JDBC
      jdbc-url: jdbc:sqlite:db.sqlite
